defmodule Advent2025.Day07Test do
  use ExUnit.Case

  @example_input """
  .......S.......
  ...............
  .......^.......
  ...............
  ......^.^......
  ...............
  .....^.^.^.....
  ...............
  ....^.^...^....
  ...............
  ...^.^...^.^...
  ...............
  ..^...^.....^..
  ...............
  .^.^.^.^.^...^.
  ...............
  """

  test "part 1" do
    assert Advent2025.Day07.part_1(@example_input) == 21
  end

  test "part 2" do
    assert Advent2025.Day07.part_2(@example_input) == 40
  end
end
